controller_manager:
  ros__parameters:
    update_rate: 10  # Hz
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    jackal_velocity_controller: 
      type: diff_drive_controller/DiffDriveController

jackal_velocity_controller:
  ros__parameters:
    type: diff_drive_controller/DiffDriveController"
    left_wheel_names: ['front_left_wheel', 'rear_left_wheel']
    right_wheel_names: ['front_right_wheel', 'rear_right_wheel']
    publish_rate: 50.0
    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.03]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 1000000.0, 1000000.0, 0.03]
    cmd_vel_timeout: 0.25
    wheel_separation: 0.262
    wheel_radius: 0.098
    wheel_separation_multiplier: 1.5 
    wheel_radius_multiplier    : 1.0
    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 2.0
    linear.x.min_velocity: -2.0
    linear.x.max_acceleration: 20.0

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 6.0
    angular.z.min_velocity: -6.0
    angular.z.max_acceleration: 25.0
    angular.z.min_acceleration: -25.0
